.SILENT:
default: code_day

INPUT = "/input.txt"
PROBLEM = "/problem.txt"
PYTH = ".py"
SLASH = "/"
DAY = "day"
X=$(DAY)$(day)
code_day:
	mkdir $(X)
	touch $(X)$(INPUT)
	touch $(X)$(PROBLEM)
	touch $(X)$(SLASH)$(X)$(PYTH)